### ISSUE TITLE
Update CMake Instructions for Ubuntu 24.04

### ISSUE THREAD

**Issue by ishaniraha** [intercreate/docs#10]
Clarify optional step for people who have upgraded to 24.04

**Comment by JPHutchins** [comment]
@ishaniraha Can you create a branch for these changes and then push to that branch instead of main?  Once the changes are ready we review them in a pull request.

**Comment by ishaniraha** [comment]
Oops, will do from here on out!

**Comment by JPHutchins** [comment]
> Oops, will do from here on out!

All of the commits look good!
