### ISSUE TITLE
usbipd install

### ISSUE THREAD

**Issue by ishaniraha** [intercreate/docs#4]
usbipd should be installed via msi instead of winget

**Comment by JPHutchins** [comment]
If I understand correctly, the WSL USB GUI MSI will install the correct version of USBIPD without needing to install USBIPD manually.  This should prevent version conflicts.

**Comment by JPHutchins** [comment]
To clarify, I think that instructions for installing WSL USB GUI replace both of these sections:

https://github.com/intercreate/docs/blob/24c024f0ac5618109d035923b43e36bd4bf50434/Windows/wsl2.md?plain=1#L100-L118

Still good to link to the USBIPD github and the Microsoft article in case someone wants to setup USB forwarding without the GUI.

**Comment by ishaniraha** [comment]
@JPHutchins
