### ISSUE TITLE
Suggest Ubuntu 24.04

### ISSUE THREAD

**Issue by JPHutchins** [intercreate/docs#7]
Despite its recent release, I think it's worth suggesting new installs go to the latest Ubuntu LTS.

**Comment by ishaniraha** [comment]
I'm getting an error with the CMake install with the newest Ubuntu (sudo bash kitware-archive.sh returns "Only Ubuntu Focal (20.04) and Jammy (22.04) are supported. Aborting.") Should I edit the CMake instructions at all?

**Comment by ishaniraha** [comment]
If running 20.04 or 22.04 use Cmake instructions, if not proceed without
